// <auto-generated />
using System;
using AiInterview.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Pgvector;

#nullable disable

namespace AiInterview.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260416121025_AddInterviewMessages")]
    partial class AddInterviewMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AiInterview.Api.Models.Entities.AiProviderSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApiKeyMasked")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("api_key_masked");

                    b.Property<string>("ApiKeyProtected")
                        .HasColumnType("text")
                        .HasColumnName("api_key_protected");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("base_url");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("MaxTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2048)
                        .HasColumnName("max_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("system_prompt");

                    b.Property<decimal>("Temperature")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasDefaultValue(0.7m)
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_ai_provider_settings");

                    b.ToTable("ai_provider_settings", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.Interview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("config")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer")
                        .HasColumnName("current_round");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_seconds");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("InterviewMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("standard")
                        .HasColumnName("interview_mode");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position_code");

                    b.Property<string[]>("QuestionTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)[]")
                        .HasColumnName("question_types")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("in_progress")
                        .HasColumnName("status");

                    b.Property<int>("TotalRounds")
                        .HasColumnType("integer")
                        .HasColumnName("total_rounds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_interviews");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("idx_interviews_created");

                    b.HasIndex("PositionCode")
                        .HasDatabaseName("idx_interviews_position");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_interviews_user");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_interviews_user_created");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_interviews_user_status");

                    b.ToTable("interviews", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.InterviewMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_id");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("message_type");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<Guid?>("RelatedQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_question_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_interview_messages");

                    b.HasIndex("InterviewId")
                        .HasDatabaseName("idx_messages_interview");

                    b.HasIndex("RelatedQuestionId")
                        .HasDatabaseName("idx_messages_related_question");

                    b.HasIndex("InterviewId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("idx_messages_interview_sequence");

                    b.ToTable("interview_messages", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.InterviewReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetailedAnalysis")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("detailed_analysis")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ExecutiveSummary")
                        .HasColumnType("text")
                        .HasColumnName("executive_summary");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_id");

                    b.Property<string[]>("LearningSuggestions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("learning_suggestions")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<string[]>("NextInterviewFocus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("next_interview_focus")
                        .HasDefaultValueSql("'{}'");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position_code");

                    b.Property<string[]>("Strengths")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("strengths")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("TrainingPlan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("training_plan")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string[]>("Weaknesses")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("weaknesses")
                        .HasDefaultValueSql("'{}'");

                    b.HasKey("Id")
                        .HasName("pk_interview_reports");

                    b.HasIndex("InterviewId")
                        .IsUnique()
                        .HasDatabaseName("idx_reports_interview");

                    b.HasIndex("OverallScore")
                        .HasDatabaseName("idx_reports_score");

                    b.HasIndex("PositionCode")
                        .HasDatabaseName("idx_reports_position");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_reports_user");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_reports_user_created");

                    b.ToTable("interview_reports", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.InterviewRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string[]>("AiFollowUps")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("ai_follow_ups")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset?>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("Context")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("context")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("FollowUpCount")
                        .HasColumnType("integer")
                        .HasColumnName("follow_up_count");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_id");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_content");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("QuestionTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("question_title");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("question_type");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("text")
                        .HasColumnName("user_answer");

                    b.Property<string>("UserInputMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("text")
                        .HasColumnName("user_input_mode");

                    b.Property<string>("VoiceTranscription")
                        .HasColumnType("text")
                        .HasColumnName("voice_transcription");

                    b.HasKey("Id")
                        .HasName("pk_interview_rounds");

                    b.HasIndex("InterviewId")
                        .HasDatabaseName("idx_rounds_interview");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("idx_rounds_question");

                    b.HasIndex("InterviewId", "RoundNumber")
                        .IsUnique()
                        .HasDatabaseName("idx_rounds_interview_number");

                    b.ToTable("interview_rounds", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.InterviewScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DimensionDetails")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("dimension_details")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("DimensionScores")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("dimension_scores")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("evaluated_at");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_id");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<decimal>("OverallScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<decimal?>("RankPercentile")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rank_percentile");

                    b.Property<string>("ScoreBreakdown")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("score_breakdown")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id")
                        .HasName("pk_interview_scores");

                    b.HasIndex("InterviewId")
                        .IsUnique()
                        .HasDatabaseName("idx_scores_interview");

                    b.HasIndex("OverallScore")
                        .HasDatabaseName("idx_scores_overall");

                    b.ToTable("interview_scores", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.KnowledgeChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_chunks");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("idx_chunks_content_hash");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("idx_chunks_document");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("idx_chunks_embedding")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("knowledge_chunks", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChunkCount")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_url");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position_code");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text")
                        .HasColumnName("processing_error");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_knowledge_documents");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_knowledge_documents_created_by");

                    b.HasIndex("PositionCode")
                        .HasDatabaseName("idx_knowledge_docs_position");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_knowledge_docs_status");

                    b.HasIndex("Tags")
                        .HasDatabaseName("idx_knowledge_docs_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.ToTable("knowledge_documents", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.LearningResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("cover_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("Duration")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duration");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position_code");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider");

                    b.Property<decimal?>("Rating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("rating");

                    b.Property<string>("ReadingTime")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reading_time");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string[]>("TargetDimensions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)[]")
                        .HasColumnName("target_dimensions")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_learning_resources");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("idx_resources_difficulty");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_resources_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("PositionCode")
                        .HasDatabaseName("idx_resources_position");

                    b.HasIndex("Tags")
                        .HasDatabaseName("idx_resources_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("TargetDimensions")
                        .HasDatabaseName("idx_resources_target_dims");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("TargetDimensions"), "gin");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_resources_type");

                    b.ToTable("learning_resources", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasAlternateKey("Code")
                        .HasName("ak_positions_code");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("idx_positions_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_positions_active")
                        .HasFilter("is_active = true");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.QuestionBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("difficulty");

                    b.Property<string>("IdealAnswer")
                        .HasColumnType("text")
                        .HasColumnName("ideal_answer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("position_code");

                    b.Property<Guid[]>("RelatedKnowledgeIds")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("related_knowledge_ids")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("ScoringRubric")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("scoring_rubric")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("integer")
                        .HasColumnName("success_count");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UseCount")
                        .HasColumnType("integer")
                        .HasColumnName("use_count");

                    b.HasKey("Id")
                        .HasName("pk_question_banks");

                    b.HasIndex("Difficulty")
                        .HasDatabaseName("idx_questions_difficulty");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_questions_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("PositionCode")
                        .HasDatabaseName("idx_questions_position");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("idx_questions_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "gin");

                    b.HasIndex("Tags")
                        .HasDatabaseName("idx_questions_tags");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_questions_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_questions_type");

                    b.HasIndex("PositionCode", "Type")
                        .HasDatabaseName("idx_questions_position_type");

                    b.ToTable("question_banks", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.RecommendationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("InterviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_viewed");

                    b.Property<string>("MatchScores")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("match_scores")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid[]>("RecommendedResources")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid[]")
                        .HasColumnName("recommended_resources")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string[]>("TargetDimensions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)[]")
                        .HasColumnName("target_dimensions")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("TrainingPlan")
                        .HasColumnType("jsonb")
                        .HasColumnName("training_plan");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_records");

                    b.HasIndex("InterviewId")
                        .HasDatabaseName("idx_recommendations_interview");

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_recommendation_records_report_id");

                    b.HasIndex("Type")
                        .HasDatabaseName("idx_recommendations_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_recommendations_user");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_recommendations_user_created");

                    b.ToTable("recommendation_records", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<string>("TargetPositionCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_position_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("TargetPositionCode")
                        .HasDatabaseName("idx_users_target_position");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("idx_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.Interview", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Position", "Position")
                        .WithMany("Interviews")
                        .HasForeignKey("PositionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interviews_positions_position_code");

                    b.HasOne("AiInterview.Api.Models.Entities.User", "User")
                        .WithMany("Interviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interviews_users_user_id");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.InterviewMessage", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Interview", "Interview")
                        .WithMany("Messages")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_messages_interviews_interview_id");

                    b.HasOne("AiInterview.Api.Models.Entities.QuestionBank", "RelatedQuestion")
                        .WithMany()
                        .HasForeignKey("RelatedQuestionId")
                        .HasConstraintName("fk_interview_messages_question_banks_related_question_id");

                    b.Navigation("Interview");

                    b.Navigation("RelatedQuestion");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.InterviewReport", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Interview", "Interview")
                        .WithOne("Report")
                        .HasForeignKey("AiInterview.Api.Models.Entities.InterviewReport", "InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_reports_interviews_interview_id");

                    b.HasOne("AiInterview.Api.Models.Entities.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_reports_positions_position_code");

                    b.HasOne("AiInterview.Api.Models.Entities.User", "User")
                        .WithMany("InterviewReports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_reports_users_user_id");

                    b.Navigation("Interview");

                    b.Navigation("Position");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.InterviewRound", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Interview", "Interview")
                        .WithMany("Rounds")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_rounds_interviews_interview_id");

                    b.HasOne("AiInterview.Api.Models.Entities.QuestionBank", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_interview_rounds_question_banks_question_id");

                    b.Navigation("Interview");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.InterviewScore", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Interview", "Interview")
                        .WithOne("Score")
                        .HasForeignKey("AiInterview.Api.Models.Entities.InterviewScore", "InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_scores_interviews_interview_id");

                    b.Navigation("Interview");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.KnowledgeChunk", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.KnowledgeDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_chunks_knowledge_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.KnowledgeDocument", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("fk_knowledge_documents_users_created_by");

                    b.HasOne("AiInterview.Api.Models.Entities.Position", "Position")
                        .WithMany("KnowledgeDocuments")
                        .HasForeignKey("PositionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_documents_positions_position_code");

                    b.Navigation("Creator");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.LearningResource", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Position", "Position")
                        .WithMany("LearningResources")
                        .HasForeignKey("PositionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_learning_resources_positions_position_code");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.QuestionBank", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Position", "Position")
                        .WithMany("QuestionBanks")
                        .HasForeignKey("PositionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_banks_positions_position_code");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.RecommendationRecord", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Interview", "Interview")
                        .WithMany()
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recommendation_records_interviews_interview_id");

                    b.HasOne("AiInterview.Api.Models.Entities.InterviewReport", "Report")
                        .WithMany()
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recommendation_records_interview_reports_report_id");

                    b.HasOne("AiInterview.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_records_users_user_id");

                    b.Navigation("Interview");

                    b.Navigation("Report");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.User", b =>
                {
                    b.HasOne("AiInterview.Api.Models.Entities.Position", "TargetPosition")
                        .WithMany()
                        .HasForeignKey("TargetPositionCode")
                        .HasPrincipalKey("Code")
                        .HasConstraintName("fk_users_positions_target_position_code");

                    b.Navigation("TargetPosition");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.Interview", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Report");

                    b.Navigation("Rounds");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.Position", b =>
                {
                    b.Navigation("Interviews");

                    b.Navigation("KnowledgeDocuments");

                    b.Navigation("LearningResources");

                    b.Navigation("QuestionBanks");
                });

            modelBuilder.Entity("AiInterview.Api.Models.Entities.User", b =>
                {
                    b.Navigation("InterviewReports");

                    b.Navigation("Interviews");
                });
#pragma warning restore 612, 618
        }
    }
}
